export const fornecedorlist = [
    {
      id: 1,
      nome: "Mercadao",
      cnpj: "1123111111",
      cep: "14256870",         
      cidade: '',
      estado: '',
      bairro: '',
      endereco: '',
      numero: '',
      complemento:'',        
    },
    {
      id: 2,
      nome: "Papelaria",
      cnpj: "2222222222",
      cep: "14987870",
      cidade: '',
      estado: '',
      endereco: '',
      bairro: '',
      numero: '',
      complemento:'', 
    },
    {
      id: 3,
      nome: "Lanchonete",
      cnpj: "3333333333",
      cep: "14265870",
      cidade: '',
      estado: '',
      bairro: '',
      endereco: '',
      numero: '',
      complemento:'', 
    },
  ];
  